@include('components.nav-tabs', ['tabs' => [
    [
        'name' => 'mapa',
        'label' => 'Mapa de red',
        'icon' => 'fas fa-map',
        'route' => route('infraestructura.mapa.index'),
        'permission' => 'infraestructura.read',
        'active' => request()->is('infraestructura/mapa*'),
    ],
    [
        'name' => 'detalle-pon',
        'label' => 'Detalle PON',
        'icon' => 'fas fa-sitemap',
        'route' => route('infraestructura.detalle-pon.index'),
        'permission' => 'infraestructura.read',
        'active' => request()->is('infraestructura/detalle-pon*'),
    ],
    [
        'name' => 'olts',
        'label' => 'OLTs',
        'icon' => 'fas fa-hdd',
        'route' => route('infraestructura.olts.index'),
        'permission' => 'infraestructura.read',
        'active' => request()->is('infraestructura/olts*'),
    ],
    [
        'name' => 'odfs',
        'label' => 'ODFs',
        'icon' => 'fas fa-th-large',
        'route' => route('infraestructura.odfs.index'),
        'permission' => 'infraestructura.read',
        'active' => request()->is('infraestructura/odfs*'),
    ],
    [
        'name' => 'postes',
        'label' => 'Postes',
        'icon' => 'fas fa-broadcast-tower',
        'route' => route('infraestructura.postes.index'),
        'permission' => 'infraestructura.read',
        'active' => request()->is('infraestructura/postes*'),
    ],
    [
        'name' => 'cajas-nap',
        'label' => 'Cajas NAP',
        'icon' => 'fas fa-box',
        'route' => route('infraestructura.cajas-nap.index'),
        'permission' => 'infraestructura.read',
        'active' => request()->is('infraestructura/cajas-nap*'),
    ],
    [
        'name' => 'mufas',
        'label' => 'Mufas',
        'icon' => 'fas fa-link',
        'route' => route('infraestructura.mufas.index'),
        'permission' => 'infraestructura.read',
        'active' => request()->is('infraestructura/mufas*'),
    ],
]])
