CREATE TABLE `api_configs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL COMMENT 'Nombre de la API (ej: apisperu)',
  `descripcion` varchar(255) DEFAULT NULL COMMENT 'Descripción de la API',
  `token` text DEFAULT NULL COMMENT 'Token o API key',
  `activo` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Si la API está activa',
  `configuracion_extra` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Configuración adicional en JSON' CHECK (json_valid(`configuracion_extra`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `api_configs_nombre_unique` (`nombre`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `audit_logs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `action` varchar(50) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `model_type` varchar(255) NOT NULL,
  `model_id` bigint(20) unsigned DEFAULT NULL,
  `model_label` varchar(255) DEFAULT NULL,
  `module` varchar(100) DEFAULT NULL,
  `old_values` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`old_values`)),
  `new_values` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`new_values`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `audit_logs_model_type_model_id_index` (`model_type`,`model_id`),
  KEY `audit_logs_user_id_index` (`user_id`),
  KEY `audit_logs_action_index` (`action`),
  KEY `audit_logs_created_at_index` (`created_at`),
  KEY `audit_logs_ip_address_index` (`ip_address`),
  KEY `audit_logs_isp_id_index` (`isp_id`),
  CONSTRAINT `audit_logs_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `audit_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cache` (
  `key` varchar(255) NOT NULL,
  `value` mediumtext NOT NULL,
  `expiration` int(11) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cache_locks` (
  `key` varchar(255) NOT NULL,
  `owner` varchar(255) NOT NULL,
  `expiration` int(11) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `clientes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `nombre` varchar(255) NOT NULL,
  `nombre_comercial` varchar(255) DEFAULT NULL,
  `estado_ruc` varchar(255) DEFAULT NULL,
  `condicion_ruc` varchar(255) DEFAULT NULL,
  `ubigeo` varchar(255) DEFAULT NULL,
  `capital` decimal(15,2) DEFAULT NULL,
  `direccion_api` varchar(255) DEFAULT NULL,
  `departamento_api` varchar(255) DEFAULT NULL,
  `provincia_api` varchar(255) DEFAULT NULL,
  `distrito_api` varchar(255) DEFAULT NULL,
  `fuente_info` varchar(255) DEFAULT NULL,
  `tipo_documento` enum('dni','ce','ruc') NOT NULL DEFAULT 'dni',
  `documento` varchar(255) NOT NULL,
  `telefonos` varchar(255) DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `clientes_documento_unique` (`documento`),
  KEY `clientes_documento_index` (`documento`),
  KEY `clientes_nombre_index` (`nombre`),
  KEY `idx_clientes_documento` (`documento`),
  KEY `idx_clientes_tipo_documento` (`tipo_documento`),
  KEY `clientes_isp_id_index` (`isp_id`),
  CONSTRAINT `clientes_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `comprobante_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `comprobante_id` bigint(20) unsigned NOT NULL,
  `orden` int(11) NOT NULL DEFAULT 1,
  `codigo_producto` varchar(50) DEFAULT NULL,
  `codigo_sunat` varchar(20) DEFAULT NULL,
  `unidad_medida` varchar(10) NOT NULL DEFAULT 'ZZ',
  `descripcion` text NOT NULL,
  `descripcion_detalle` text DEFAULT NULL,
  `cantidad` decimal(12,4) NOT NULL DEFAULT 1.0000,
  `precio_unitario` decimal(12,4) NOT NULL,
  `valor_unitario` decimal(12,4) DEFAULT NULL,
  `descuento` decimal(12,2) NOT NULL DEFAULT 0.00,
  `subtotal` decimal(12,2) NOT NULL,
  `igv` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total` decimal(12,2) NOT NULL,
  `tipo_afectacion_igv` varchar(10) NOT NULL DEFAULT '10',
  `porcentaje_igv` decimal(5,2) NOT NULL DEFAULT 18.00,
  `servicio_id` bigint(20) unsigned DEFAULT NULL,
  `recibo_id` bigint(20) unsigned DEFAULT NULL,
  `periodo` varchar(20) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `comprobante_items_servicio_id_foreign` (`servicio_id`),
  KEY `comprobante_items_recibo_id_foreign` (`recibo_id`),
  KEY `comprobante_items_comprobante_id_orden_index` (`comprobante_id`,`orden`),
  KEY `comprobante_items_isp_id_index` (`isp_id`),
  CONSTRAINT `comprobante_items_comprobante_id_foreign` FOREIGN KEY (`comprobante_id`) REFERENCES `comprobantes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comprobante_items_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comprobante_items_recibo_id_foreign` FOREIGN KEY (`recibo_id`) REFERENCES `recibos` (`id`) ON DELETE SET NULL,
  CONSTRAINT `comprobante_items_servicio_id_foreign` FOREIGN KEY (`servicio_id`) REFERENCES `servicios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `comprobantes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `pago_id` bigint(20) unsigned DEFAULT NULL,
  `cliente_id` bigint(20) unsigned NOT NULL,
  `cliente_direccion` varchar(255) DEFAULT NULL,
  `cliente_tipo_documento` varchar(10) DEFAULT NULL,
  `cliente_documento` varchar(20) DEFAULT NULL,
  `cliente_nombre` varchar(255) DEFAULT NULL,
  `tipo` varchar(20) NOT NULL,
  `serie` varchar(10) NOT NULL,
  `numero` int(10) unsigned NOT NULL,
  `numero_completo` varchar(50) NOT NULL,
  `fecha_emision` date NOT NULL,
  `monto` decimal(10,2) NOT NULL,
  `exonerado_igv` tinyint(1) NOT NULL DEFAULT 1,
  `descuento` decimal(12,2) NOT NULL DEFAULT 0.00,
  `igv` decimal(12,2) NOT NULL DEFAULT 0.00,
  `subtotal` decimal(12,2) DEFAULT NULL,
  `tipo_cambio` decimal(10,4) DEFAULT NULL,
  `moneda` varchar(10) NOT NULL DEFAULT 'PEN',
  `estado` varchar(20) NOT NULL DEFAULT 'vigente',
  `motivo_anulacion` text DEFAULT NULL,
  `anulado_por` bigint(20) unsigned DEFAULT NULL,
  `anulado_at` timestamp NULL DEFAULT NULL,
  `anulado` tinyint(1) NOT NULL DEFAULT 0,
  `fecha_fin_servicio` date DEFAULT NULL,
  `fecha_inicio_servicio` date DEFAULT NULL,
  `periodo_servicio` varchar(20) DEFAULT NULL,
  `motivo_nota` text DEFAULT NULL,
  `tipo_nota` varchar(20) DEFAULT NULL,
  `comprobante_referencia_id` bigint(20) unsigned DEFAULT NULL,
  `orden_compra` varchar(50) DEFAULT NULL,
  `guia_remision` varchar(50) DEFAULT NULL,
  `condiciones_pago` text DEFAULT NULL,
  `fecha_vencimiento_pago` date DEFAULT NULL,
  `forma_pago` varchar(50) NOT NULL DEFAULT 'contado',
  `enviado_sunat` tinyint(1) NOT NULL DEFAULT 0,
  `enviado_sunat_at` timestamp NULL DEFAULT NULL,
  `ticket_sunat` varchar(50) DEFAULT NULL,
  `mensaje_respuesta` text DEFAULT NULL,
  `codigo_respuesta` varchar(10) DEFAULT NULL,
  `hash` varchar(100) DEFAULT NULL,
  `generado_por` bigint(20) unsigned DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `comprobantes_generado_por_foreign` (`generado_por`),
  KEY `comprobantes_tipo_serie_numero_index` (`tipo`,`serie`,`numero`),
  KEY `comprobantes_numero_completo_index` (`numero_completo`),
  KEY `comprobantes_cliente_id_index` (`cliente_id`),
  KEY `comprobantes_pago_id_index` (`pago_id`),
  KEY `comprobantes_isp_id_index` (`isp_id`),
  CONSTRAINT `comprobantes_cliente_id_foreign` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comprobantes_generado_por_foreign` FOREIGN KEY (`generado_por`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `comprobantes_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comprobantes_pago_id_foreign` FOREIGN KEY (`pago_id`) REFERENCES `pagos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `isps` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  `ruc` varchar(255) DEFAULT NULL,
  `direccion` text DEFAULT NULL,
  `telefono` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `activo` tinyint(1) NOT NULL DEFAULT 1,
  `moneda` varchar(3) NOT NULL DEFAULT 'PEN',
  `simbolo_moneda` varchar(10) NOT NULL DEFAULT 'S/.',
  `igv` decimal(5,2) NOT NULL DEFAULT 18.00,
  `dia_emision` tinyint(4) NOT NULL DEFAULT 1,
  `dias_gracia` tinyint(4) NOT NULL DEFAULT 5,
  `dias_vencimiento` tinyint(4) NOT NULL DEFAULT 15,
  `generar_recibos_automaticos` tinyint(1) NOT NULL DEFAULT 1,
  `serie_boleta` varchar(20) NOT NULL DEFAULT 'B001',
  `serie_factura` varchar(20) NOT NULL DEFAULT 'F001',
  `corte_automatico` tinyint(1) NOT NULL DEFAULT 1,
  `dias_antes_corte` tinyint(4) NOT NULL DEFAULT 0,
  `reactivacion_automatica` tinyint(1) NOT NULL DEFAULT 1,
  `notificar_vencimiento` tinyint(1) NOT NULL DEFAULT 1,
  `dias_notificacion_vencimiento` tinyint(4) NOT NULL DEFAULT 3,
  `whatsapp_habilitado` tinyint(1) NOT NULL DEFAULT 0,
  `email_habilitado` tinyint(1) NOT NULL DEFAULT 0,
  `sms_habilitado` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `isps_ruc_unique` (`ruc`),
  KEY `isps_activo_index` (`activo`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `medios_pago` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `nombre` varchar(255) NOT NULL,
  `tipo` enum('yape','transferencia','efectivo','plin','otro') NOT NULL DEFAULT 'yape',
  `numero_cuenta` varchar(255) DEFAULT NULL,
  `banco` varchar(255) DEFAULT NULL,
  `activo` tinyint(1) NOT NULL DEFAULT 1,
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `medios_pago_tipo_index` (`tipo`),
  KEY `medios_pago_activo_index` (`activo`),
  KEY `medios_pago_isp_id_index` (`isp_id`),
  CONSTRAINT `medios_pago_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `nodos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `nombre` varchar(255) NOT NULL,
  `ubicacion` varchar(255) DEFAULT NULL,
  `descripcion` text DEFAULT NULL,
  `estado` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `nodos_isp_id_index` (`isp_id`),
  CONSTRAINT `nodos_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `onu_marcas` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `nombre` varchar(255) NOT NULL,
  `estado` tinyint(1) NOT NULL DEFAULT 1,
  `orden` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `onu_marcas_nombre_unique` (`nombre`),
  KEY `onu_marcas_isp_id_index` (`isp_id`),
  CONSTRAINT `onu_marcas_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `onu_modelos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `marca_id` bigint(20) unsigned NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `requiere_transformacion` tinyint(1) NOT NULL DEFAULT 0,
  `usuario_pppoe_default` varchar(255) DEFAULT NULL,
  `password_pppoe_default` varchar(255) DEFAULT NULL,
  `vlan_default` varchar(255) DEFAULT NULL,
  `tipo_conexion_default` enum('pppoe_usuario_unico','pppoe_usuario_compartido','dhcp_dinamico','pppoe_vlan') DEFAULT NULL,
  `estado` tinyint(1) NOT NULL DEFAULT 1,
  `orden` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `onu_modelos_marca_id_nombre_unique` (`marca_id`,`nombre`),
  KEY `onu_modelos_isp_id_index` (`isp_id`),
  CONSTRAINT `onu_modelos_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `onu_modelos_marca_id_foreign` FOREIGN KEY (`marca_id`) REFERENCES `onu_marcas` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `onus` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `servicio_id` bigint(20) unsigned DEFAULT NULL,
  `serial_number` varchar(255) NOT NULL,
  `serial_number_completo` varchar(255) DEFAULT NULL,
  `serial_number_olt` varchar(255) DEFAULT NULL,
  `mac_address` varchar(17) NOT NULL,
  `usuario` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `marca` varchar(255) DEFAULT NULL,
  `modelo` varchar(255) DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `onus_serial_number_unique` (`serial_number`),
  KEY `onus_serial_number_index` (`serial_number`),
  KEY `onus_mac_address_index` (`mac_address`),
  KEY `onus_servicio_id_foreign` (`servicio_id`),
  KEY `onus_serial_number_completo_index` (`serial_number_completo`),
  KEY `onus_serial_number_olt_index` (`serial_number_olt`),
  KEY `onus_isp_id_index` (`isp_id`),
  CONSTRAINT `onus_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `onus_servicio_id_foreign` FOREIGN KEY (`servicio_id`) REFERENCES `servicios` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `pagos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `cliente_id` bigint(20) unsigned NOT NULL,
  `servicio_id` bigint(20) unsigned DEFAULT NULL,
  `recibo_id` bigint(20) unsigned DEFAULT NULL,
  `monto` decimal(10,2) NOT NULL,
  `fecha_pago` date NOT NULL,
  `fecha_hora` datetime DEFAULT NULL,
  `codigo_seguridad` varchar(10) DEFAULT NULL,
  `numero_operacion` varchar(50) DEFAULT NULL,
  `captura` varchar(255) DEFAULT NULL,
  `registrado_por` bigint(20) unsigned DEFAULT NULL,
  `medio_pago` enum('efectivo','yape','transferencia','plin','otro') NOT NULL DEFAULT 'efectivo',
  `medio_pago_id` bigint(20) unsigned DEFAULT NULL,
  `referencia` varchar(255) DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pagos_servicio_id_foreign` (`servicio_id`),
  KEY `pagos_fecha_pago_index` (`fecha_pago`),
  KEY `pagos_medio_pago_index` (`medio_pago`),
  KEY `pagos_medio_pago_id_foreign` (`medio_pago_id`),
  KEY `pagos_fecha_hora_index` (`fecha_hora`),
  KEY `pagos_numero_operacion_index` (`numero_operacion`),
  KEY `pagos_registrado_por_index` (`registrado_por`),
  KEY `pagos_codigo_seguridad_index` (`codigo_seguridad`),
  KEY `pagos_codigo_numero_index` (`codigo_seguridad`,`numero_operacion`),
  KEY `idx_pagos_cliente_id` (`cliente_id`),
  KEY `idx_pagos_fecha_pago` (`fecha_pago`),
  KEY `pagos_recibo_id_foreign` (`recibo_id`),
  KEY `pagos_isp_id_index` (`isp_id`),
  CONSTRAINT `pagos_cliente_id_foreign` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `pagos_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `pagos_medio_pago_id_foreign` FOREIGN KEY (`medio_pago_id`) REFERENCES `medios_pago` (`id`) ON DELETE SET NULL,
  CONSTRAINT `pagos_recibo_id_foreign` FOREIGN KEY (`recibo_id`) REFERENCES `recibos` (`id`) ON DELETE SET NULL,
  CONSTRAINT `pagos_registrado_por_foreign` FOREIGN KEY (`registrado_por`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `pagos_servicio_id_foreign` FOREIGN KEY (`servicio_id`) REFERENCES `servicios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `permission_role` (
  `permission_id` bigint(20) unsigned NOT NULL,
  `role_id` bigint(20) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`permission_id`,`role_id`),
  KEY `permission_role_role_id_foreign` (`role_id`),
  CONSTRAINT `permission_role_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `permission_role_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `permissions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `display_name` varchar(255) NOT NULL,
  `module` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `is_hidden` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `permissions_name_unique` (`name`),
  KEY `permissions_isp_id_index` (`isp_id`),
  KEY `idx_permissions_module` (`module`),
  CONSTRAINT `permissions_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `planes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `router_id` bigint(20) unsigned DEFAULT NULL,
  `nombre` varchar(255) NOT NULL,
  `categoria` enum('Hogar','Empresa','Dedicado','Wireless','FTTH') NOT NULL DEFAULT 'Hogar',
  `estado` tinyint(1) NOT NULL DEFAULT 1,
  `velocidad_bajada_mbps` int(11) NOT NULL,
  `velocidad_subida_mbps` int(11) NOT NULL,
  `precio_mensual` decimal(10,2) NOT NULL,
  `tipo_conexion` enum('pppoe_usuario_unico','pppoe_usuario_compartido','ip_estatica','dhcp_dinamico','ip_fija_vlan','pppoe_vlan') NOT NULL DEFAULT 'pppoe_usuario_unico',
  `perfil_mikrotik` varchar(255) DEFAULT NULL,
  `local_address` varchar(255) DEFAULT NULL,
  `remote_address` varchar(255) DEFAULT NULL,
  `dns` varchar(255) DEFAULT NULL,
  `rate_limit` varchar(255) DEFAULT NULL,
  `asignacion_ip` enum('dinamica','estatica','pool') NOT NULL DEFAULT 'dinamica',
  `ip_fija` varchar(255) DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `planes_router_id_foreign` (`router_id`),
  KEY `planes_isp_id_index` (`isp_id`),
  CONSTRAINT `planes_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `planes_router_id_foreign` FOREIGN KEY (`router_id`) REFERENCES `routers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `plantillas_whatsapp` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tipo` varchar(255) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `mensaje` text NOT NULL,
  `activo` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `plantilla_whats_apps_tipo_unique` (`tipo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `promesas_pago` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `recibo_id` bigint(20) unsigned NOT NULL,
  `cliente_id` bigint(20) unsigned NOT NULL,
  `servicio_id` bigint(20) unsigned DEFAULT NULL,
  `fecha_compromiso` date NOT NULL,
  `monto_comprometido` decimal(10,2) NOT NULL,
  `estado` enum('pendiente','cumplida','vencida','cancelada') NOT NULL DEFAULT 'pendiente',
  `observacion` text DEFAULT NULL,
  `creado_por` bigint(20) unsigned DEFAULT NULL,
  `cumplida_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `promesas_pago_servicio_id_foreign` (`servicio_id`),
  KEY `promesas_pago_creado_por_foreign` (`creado_por`),
  KEY `promesas_pago_cliente_id_estado_index` (`cliente_id`,`estado`),
  KEY `promesas_pago_fecha_compromiso_index` (`fecha_compromiso`),
  KEY `idx_promesas_cliente_id` (`cliente_id`),
  KEY `idx_promesas_estado` (`estado`),
  KEY `idx_promesas_fecha_compromiso` (`fecha_compromiso`),
  KEY `promesas_pago_recibo_id_estado_index` (`recibo_id`,`estado`),
  KEY `promesas_pago_isp_id_index` (`isp_id`),
  CONSTRAINT `promesas_pago_cliente_id_foreign` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `promesas_pago_creado_por_foreign` FOREIGN KEY (`creado_por`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `promesas_pago_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `promesas_pago_recibo_id_foreign` FOREIGN KEY (`recibo_id`) REFERENCES `recibos` (`id`) ON DELETE CASCADE,
  CONSTRAINT `promesas_pago_servicio_id_foreign` FOREIGN KEY (`servicio_id`) REFERENCES `servicios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `recibos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `codigo` varchar(20) DEFAULT NULL,
  `cliente_id` bigint(20) unsigned NOT NULL,
  `servicio_id` bigint(20) unsigned DEFAULT NULL,
  `periodo` varchar(7) NOT NULL,
  `fecha_emision` date NOT NULL,
  `fecha_vencimiento` date NOT NULL,
  `monto` decimal(10,2) NOT NULL,
  `saldo` decimal(10,2) NOT NULL DEFAULT 0.00,
  `estado` enum('pendiente','pagado','vencido') NOT NULL DEFAULT 'pendiente',
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `deudas_servicio_periodo_unique` (`servicio_id`,`periodo`),
  UNIQUE KEY `deudas_codigo_unique` (`codigo`),
  KEY `deudas_periodo_index` (`periodo`),
  KEY `deudas_estado_index` (`estado`),
  KEY `deudas_cliente_id_periodo_index` (`cliente_id`,`periodo`),
  KEY `deudas_saldo_index` (`saldo`),
  KEY `deudas_fecha_vencimiento_index` (`fecha_vencimiento`),
  KEY `deudas_estado_saldo_index` (`estado`,`saldo`),
  KEY `idx_deudas_cliente_id` (`cliente_id`),
  KEY `idx_deudas_servicio_id` (`servicio_id`),
  KEY `idx_deudas_estado` (`estado`),
  KEY `idx_deudas_cliente_periodo` (`cliente_id`,`periodo`),
  KEY `idx_deudas_servicio_periodo` (`servicio_id`,`periodo`),
  KEY `idx_deudas_cliente_estado_saldo` (`cliente_id`,`estado`,`saldo`),
  KEY `idx_deudas_cliente_estado_vencimiento_saldo` (`cliente_id`,`estado`,`fecha_vencimiento`,`saldo`),
  KEY `recibos_isp_id_index` (`isp_id`),
  KEY `idx_recibos_cliente_id` (`cliente_id`),
  KEY `idx_recibos_servicio_id` (`servicio_id`),
  KEY `idx_recibos_estado` (`estado`),
  KEY `idx_recibos_saldo` (`saldo`),
  KEY `idx_recibos_fecha_vencimiento` (`fecha_vencimiento`),
  KEY `idx_recibos_periodo` (`periodo`),
  KEY `idx_recibos_estado_saldo` (`estado`,`saldo`),
  KEY `idx_recibos_estado_vencimiento` (`estado`,`fecha_vencimiento`),
  KEY `idx_recibos_cliente_periodo` (`cliente_id`,`periodo`),
  KEY `idx_recibos_cliente_estado` (`cliente_id`,`estado`),
  CONSTRAINT `deudas_cliente_id_foreign` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `deudas_servicio_id_foreign` FOREIGN KEY (`servicio_id`) REFERENCES `servicios` (`id`) ON DELETE SET NULL,
  CONSTRAINT `recibos_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `reglas` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `router_id` bigint(20) unsigned NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `tipo` varchar(255) NOT NULL DEFAULT 'firewall',
  `configuracion` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`configuracion`)),
  `activo` tinyint(1) NOT NULL DEFAULT 1,
  `exportado` tinyint(1) NOT NULL DEFAULT 0,
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `reglas_router_id_foreign` (`router_id`),
  KEY `reglas_isp_id_index` (`isp_id`),
  CONSTRAINT `reglas_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `reglas_router_id_foreign` FOREIGN KEY (`router_id`) REFERENCES `routers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `roles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `roles_name_unique` (`name`),
  KEY `roles_isp_id_index` (`isp_id`),
  CONSTRAINT `roles_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `routers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `nombre` varchar(255) NOT NULL,
  `ip_url` varchar(255) NOT NULL,
  `puerto_api` int(11) DEFAULT NULL,
  `puerto_snmp` int(11) DEFAULT NULL,
  `comunidad` varchar(255) DEFAULT NULL,
  `usuario` varchar(255) DEFAULT NULL,
  `contraseña` varchar(255) DEFAULT NULL,
  `nodo_id` bigint(20) unsigned DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `estado` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `routers_nodo_id_foreign` (`nodo_id`),
  KEY `routers_isp_id_index` (`isp_id`),
  CONSTRAINT `routers_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `routers_nodo_id_foreign` FOREIGN KEY (`nodo_id`) REFERENCES `nodos` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `series_comprobantes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `tipo` varchar(20) NOT NULL,
  `serie` varchar(10) NOT NULL,
  `ultimo_numero` int(11) NOT NULL DEFAULT 0,
  `activo` tinyint(1) NOT NULL DEFAULT 1,
  `descripcion` varchar(255) DEFAULT NULL,
  `genera_automatico` tinyint(1) NOT NULL DEFAULT 1,
  `envia_sunat` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `series_comprobantes_tipo_serie_unique` (`tipo`,`serie`),
  KEY `series_comprobantes_isp_id_index` (`isp_id`),
  CONSTRAINT `series_comprobantes_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `servicios` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `ubicacion_id` bigint(20) unsigned NOT NULL,
  `router_id` bigint(20) unsigned NOT NULL,
  `plan_id` bigint(20) unsigned NOT NULL,
  `tipo_pppoe` enum('unico','diferente') NOT NULL DEFAULT 'diferente',
  `usuario_pppoe` varchar(255) DEFAULT NULL,
  `password_pppoe` varchar(255) DEFAULT NULL,
  `mac_address` varchar(17) NOT NULL,
  `estado` enum('activo','cortado') NOT NULL DEFAULT 'activo',
  `es_provisional` tinyint(1) NOT NULL DEFAULT 0,
  `fecha_activacion_definitiva` timestamp NULL DEFAULT NULL,
  `fecha_instalacion` date DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `servicios_es_provisional_index` (`es_provisional`),
  KEY `servicios_estado_index` (`estado`),
  KEY `idx_servicios_mac_address` (`mac_address`),
  KEY `servicios_ubicacion_id_foreign` (`ubicacion_id`),
  KEY `servicios_isp_id_index` (`isp_id`),
  CONSTRAINT `servicios_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `servicios_ubicacion_id_foreign` FOREIGN KEY (`ubicacion_id`) REFERENCES `ubicaciones` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ubicaciones` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `cliente_id` bigint(20) unsigned DEFAULT NULL,
  `router_id` bigint(20) unsigned DEFAULT NULL,
  `direccion` varchar(255) NOT NULL,
  `referencia` varchar(255) DEFAULT NULL,
  `distrito` varchar(255) DEFAULT NULL,
  `provincia` varchar(255) DEFAULT NULL,
  `departamento` varchar(255) DEFAULT NULL,
  `latitud` decimal(10,8) DEFAULT NULL,
  `longitud` decimal(11,8) DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ubicacions_cliente_id_foreign` (`cliente_id`),
  KEY `ubicaciones_isp_id_index` (`isp_id`),
  CONSTRAINT `ubicaciones_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ubicacions_cliente_id_foreign` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `isp_id` bigint(20) unsigned DEFAULT NULL,
  `is_default_admin` tinyint(1) NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `role_id` bigint(20) unsigned DEFAULT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `users_isp_id_index` (`isp_id`),
  KEY `users_is_default_admin_index` (`is_default_admin`),
  KEY `idx_users_role_id` (`role_id`),
  CONSTRAINT `users_isp_id_foreign` FOREIGN KEY (`isp_id`) REFERENCES `isps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `users_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;